### ISSUE TITLE
Sometimes not initialized correctly

### ISSUE THREAD

**Issue by MeikelLP** [serdarciplak/BlazorMonaco#126]
I'm pretty new to Blazor and am not that good at debugging.

I'm running in rendermode `InteractiveServer` (otherwise its not working at all).

* When I navigate to a form that has this editor it doesn't get initialized correctly. There are no errors anywhere
![image](https://github.com/serdarciplak/BlazorMonaco/assets/11669846/68e4a275-2622-49b5-ab87-210a5bb4c4aa)
* When I refresh that page the editor is initialized correctly.
* When I open another page with other content, the old content is displayed but without CSS (?) instead of a new fresh editor
* I also tried to set unique IDs for each editor but without success

**Comment by obaki102** [comment]
I'm having the same issue when it comes to a Blazor web app, while my other WebAssembly project works fine.

**Comment by obaki102** [comment]
I found a workaround. It seems that if you set your _render mode_ on a per-component basis, the necessary JavaScript script files from Monaco are not loaded properly when establishing a web socket connection  or when downloading the DLL in WebAssembly mode. That's why you notice a delay and sometimes a full page reload is needed for the text editor to work.

So, in order for it to work, you need to establish a WebSocket connection readily when accessing the page. This can be achieved by setting the render mode globally. In this case, I choose _'InteractiveAuto'_ and add it to the Routes in the **App.razor** page.

`<Routes @rendermode="InteractiveAuto" />`

Finally, I moved all my  pages that needs interactivity into the client project, including my layout, and the **Routes.razor** page.

![image](https://github.com/serdarciplak/BlazorMonaco/assets/50490077/8fdc4f90-95ee-4935-96ce-fcc1a5a2b060)

For more info you can [check](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0)

**Comment by psantosl** [comment]
Thanks @obaki102 ! In my case, using blazor server, I fixed it like this, following your instructions:

`<Routes @rendermode="InteractiveServer"/>`

Now, what is the reason for this?? I don't understand it!

**Comment by serdarciplak** [comment]
Hi! I have added a troubleshooting section to the next version's README file. The two questions below should explain what the issue is and how to fix it. Let me know if these don't work for you.

- ***Q:*** The editor does not initialize correctly in my Blazor web app.

  ***A:*** To be able to work with the interactive MonacoEditor JS library, BlazorMonaco requires an interactive render mode. If you place the editor instance in a page that uses static server-side rendering (static SSR), the editor instance cannot initialize and work.

  You can set an interactive render mode globally at the app level,
  ```razor
  <!-- In your App.razor file -->
  <Routes @rendermode="InteractiveServer" />
  ```

  only for a specific page,
  ```razor
  <!-- In the razor file of your page that contains the editor -->
  @page "/editor-page"
  @rendermode InteractiveServer

  <StandaloneCodeEditor />
  ```

  or only for a component that wraps the editor instance.
  ```razor
  <!-- In the razor file of your interactive wrapper component -->
  @rendermode InteractiveServer

  <StandaloneCodeEditor />
  ```

- ***Q:*** The editor works OK the first time it's displayed. But it is broken (as if its css style is incorrect), if the user navigates to another page and returns back to the editor's page.

  ***A:*** Please check that the page that contains the editor instance is not opened with Blazor enhanced navigation. Enhanced navigation undos dynamic changes made to the DOM by MonacoEditor JS library and breaks the editor. You need to disable enhanced navigation for pages that contain an editor.

  You can set the `data-enhance-nav` attribute of your links to `false`,
  ```html
  <a href="editor-page" data-enhance-nav="false">Editor Page</a>
  ```
  set `forceLoad` parameter in your `NavigateTo()` calls to true,
  ```csharp
  Navigation.NavigateTo("editor-page", true);
  ```
  or use the Blazor docs [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-9.0#enhanced-navigation-and-form-handling) to see all methods for disabling enhanced navigation.
