### ISSUE TITLE
Editor is rendering squashed

### ISSUE THREAD

**Issue by jstafford5380** [serdarciplak/BlazorMonaco#24]
![image](https://user-images.githubusercontent.com/47302800/102533815-1d278000-4063-11eb-9f39-a71c5c97d842.png)

Is there any reason it would render like this out of the box? I don't have any css applied, but it seems to be rendering at 5px in height

**Comment by jstafford5380** [comment]
Minimal recreation: https://github.com/jstafford5380/issue-smashed-monaco

**Comment by julivanespi** [comment]
@jstafford5380 

I also ran into this. What worked for me is the following
```
<MonacoEditor Id="any-id-string" ConstructionOptions="EditorConstructionOptions" CssClass="editor-class"/>



<style>
    .editor-class{
        height: 500px;
    }
</style>
```

I think it would be better if the element filled it's parent element completely. However, in it's current state, the "CssClass" field should be required so it can give the developer an indication to add additional styling. 

Hopefully this helps...

**Comment by serdarciplak** [comment]
Hi @jstafford5380 and @julivanespi 

As you know, filling the remaining space in the parent element in html is not as straight-forward as just setting the height to 100%. It depends on the properties of the parent and the sibling elements. So, leaving this task to you (the library consumer) was the best option. You can set the height due to your case.

As there's already a predefined css class for the editor container element, you don't need to add an extra CssClass. Just set the properties you need via this class.

`
.monaco-editor-container {
    height: 100%;
}
`
