### ISSUE TITLE
Does this work with Blazor Server?

### ISSUE THREAD

**Issue by jmuronis** [serdarciplak/BlazorMonaco#42]
Does this work with Blazor Server? I tried and no matter where I put the script tags I either get an error or if I get rid of the error, then page navigation stops working.

**Comment by TheNameIsDono** [comment]
I got it working by putting the scripts last in the chain, under the _framework/blazor.server.js. 
Using NETCore 3.1

**Comment by MariaCobretti** [comment]
got to add options

#43

**Comment by QianMoXi** [comment]
Because static [IJSRuntime](https://github.com/serdarciplak/BlazorMonaco/blob/a4ee5ce5e903d0c9de38c7b5b1bf0c24b885e395/BlazorMonaco/Helpers/JsRuntimeExt.cs#L11) is used in the JsRuntimeExt , It cannot be used on Blazor Server, otherwise it will cause data spoofing when multiple people open the editor

**Comment by serdarciplak** [comment]
#98 fixes the static `IJSRuntime` issue and it should now be compatible with server-side apps. To sum up, server-side apps does not use the static instance but expects the app to provide an instance when one is needed.

Let me know if there are any other issues.
