### ISSUE TITLE
BlazorMonaco.Environment overlap with System.Environment

### ISSUE THREAD

**Issue by svenboulanger** [serdarciplak/BlazorMonaco#73]
When including `BlazorMonaco` and `System` which would happen quite commonly, there is always an ambiguous reference to `Environment` (like when using `Environment.Newline`).

More of a user-experience issue than a bug though. People can simply qualify the full namespace where necessary.

**Comment by serdarciplak** [comment]
As the `BlazorMonaco.Environment` class is not currently used, I can remove it until it's used. But that will be just postponing the issue. Or, another similar name overlap may occur in any other place with any other namespace. I think the best way to handle this issue is using the full class name to get rid of the ambiguity, like you did.
