### ISSUE TITLE
How can I decorate a line?

### ISSUE THREAD

**Issue by elgransan** [serdarciplak/BlazorMonaco#94]
I found on javascript version to decorate a line I must write the following code:

![image](https://github.com/serdarciplak/BlazorMonaco/assets/9949584/b9defcc8-3803-42d7-8304-a0dd154d3de0)

But I couldn't find the way to do this with your wrapper. It is possible?

Thanks!

**Comment by Ghevi** [comment]
Try this, not sure if it's the best, the `_codeEditor` is a reference to the Blazor component you are using.
![Screenshot 2023-07-24 130510](https://github.com/serdarciplak/BlazorMonaco/assets/39503352/64e8d64e-79fe-4f7e-bb7c-459dcd5d5d03)

I'm keeping track of the old decorations because in my case i need to update them when the model changes but for some reason they don't get updated.

**Comment by elgransan** [comment]
Ahhh nice workaround, thanks!
